name: Auto Build & Release EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install FFmpeg
      run: |
        choco install ffmpeg -y

    
    - name: Generate version
      id: version
      shell: powershell
      run: |
        $version = "v1.0.$env:GITHUB_RUN_NUMBER"
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT

    - name: Build EXE
      run: |
        pyinstaller --onefile `
                    --noconsole `
                    --icon=icon/icon.ico `
                    --name=YoutubeMP3 `
                    pyfixmp3.py

    - name: Rename EXE
      run: |
        move dist/YoutubeMP3.exe ${{ steps.version.outputs.VERSION }}-YoutubeMP3.exe

  
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YoutubeMP3
        path: YoutubeMP3-${{ steps.version.outputs.VERSION }}.exe

   
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        files: ${{ steps.version.outputs.VERSION }}-YoutubeMP3.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
